### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by fliiiix** [Binaergewitter/statiker#1]
Ich hoffe es ist ok wenn wir die Diskussion von https://github.com/Binaergewitter/serious-bg/pull/282 hier weiterführen.

> deployen wie man lustig ist im target Repo sollte halt nur nicht das selbe sein wie Statiker  

Mir ist immer noch nicht ganz klar warum wir das nicht ins gleiche repo deployen können sollen. 
Bzw was dagegen spricht? 

Sorry der issue hier war irgendwie nur bei mir im browser aber ich hab ihn nie submitted :confused:

**Comment by sukramlitt** [comment]
Eigentlich nichts mir waren ein oder zwei technische Details für GitHub
Pages noch nicht klar. Vergiss daher meine vorherigen Annahmen. Wenn wir
das Branch based machen sollte es auch problemlos in einem repo gehen

Felix <notifications@github.com> schrieb am So., 21. Okt. 2018, 10:23:

**Comment by fliiiix** [comment]
Gut dann sehe ich das als erledigt an. Fals wir doch ein extra repo fürs deployment brauchen sag Bescheid und dann können wir dir eins anlegen. :+1:
